domain: docs.routingk.it
url: https://docs.routingk.it/
baseurl: /
title: RoutingK.it - Documentation
description: Documentation for the RoutingK.it Projects
remote_theme: just-the-docs/just-the-docs-template

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
